### ISSUE TITLE
What do these extensions do and how to use them

### ISSUE THREAD

**Issue by bluelephant825** [Smile4ever/mycroftproject-query#1]
Hi @Smile4ever , I tried to understand what the extension mycroftproject-search-webext does and how to it from looking at the code, but I didn't get it! I'm still looking for a way to easily add a search engine from mycroftproject into Context Search.

**Comment by Smile4ever** [comment]
Hi @odebroqueville

It has been a while since I wrote that extension. So I had to dig it up.

Initially it opens http://mycroftproject.com/search-engines.html when you click on the browser action button. And that's all it does, but..

the planned feature was to retrieve the XML from the search engine and feed that to Context Search. However, this functionality was never finished.

https://github.com/Smile4ever/mycroftproject-query/blob/master/mycroftproject-search-webext/mycroftproject-search.js contains the logic to extract the necessary data from the XML file. You can use it in your Context Search extension if you want.

**Comment by bluelephant825** [comment]
Hi @Smile4ever , thanks for getting back to me on this. I was finally able to implement something in Context Search. Now, if you visit mycroftproject.com and right-click on one of the listed search engines, it will be added to Context Search. I haven't released it on AMO yet, still only on GitHub. Thanks again and be well. Btw, I've adopted Neat_Url... I like but I think it broke my login for medium.com.

**Comment by Smile4ever** [comment]
I'm glad you were able to sort out something.

If you have an issue with Neat URL, please open one here so we can work to resolve it: https://github.com/Smile4ever/Neat-URL/issues/

**Comment by bluelephant825** [comment]
Sorry for the late response, but I made a mistake: neat_url does not break my login into medium.com. It's another extension that breaks my medium login. Cheers and thank you.
